### ISSUE TITLE
Which 8051 for beginner?

### ISSUE THREAD

**Issue by larsbrinkhoff** [jamesbowman/8051forth#1]
Hello,

I'd like to ask your advice.  Do you know a 8051 part which is easy to use for a beginner?  Preferrably one which can be programmed with a command-line tool in Linux, and is simple to connect to a PC (USB?).

Thanks!

**Comment by jamesbowman** [comment]
Hmm, I am using two 8051 parts: the CC1110 and the Silicon Labs series.
Neither are supported by Linux as far as I know - both require proprietary programmer hardware that only runs under their IDE.

However the CC1110 debug/flash protocol is fully documented. I have some tools to program it that I am running on Raspberry Pi - would that help?

**Comment by larsbrinkhoff** [comment]
Thank you.  That might help in the future, but for now I'm looking for something more plug-and-play.

SiLabs' Simplicity Studio does run on Linux.  There's even an undocumented command line tool for programming.  But I haven't been able to make it work with my ToolStick yet.
